/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-tint": "#565e74",
              "on-tertiary-container": "#818486",
              "on-secondary-fixed-variant": "#005048",
              "surface-variant": "#d3e4fe",
              "primary-fixed": "#dae2fd",
              "inverse-on-surface": "#eaf1ff",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed-variant": "#444749",
              "surface-container-high": "#dce9ff",
              "primary-fixed-dim": "#bec6e0",
              "tertiary-fixed": "#e0e3e5",
              "error-container": "#ffdad6",
              "on-tertiary-fixed": "#191c1e",
              "on-primary-fixed": "#131b2e",
              "surface-container-low": "#eff4ff",
              "error": "#ba1a1a",
              "on-surface": "#0b1c30",
              "on-secondary-fixed": "#00201c",
              "on-background": "#0b1c30",
              "surface": "#f8f9ff",
              "on-error-container": "#93000a",
              "on-secondary-container": "#006f64",
              "tertiary": "#000000",
              "surface-bright": "#f8f9ff",
              "tertiary-fixed-dim": "#c4c7c9",
              "on-primary": "#ffffff",
              "secondary-container": "#6df5e1",
              "on-primary-container": "#7c839b",
              "primary": "#000000",
              "outline-variant": "#c6c6cd",
              "on-surface-variant": "#45464d",
              "inverse-surface": "#213145",
              "surface-dim": "#cbdbf5",
              "on-tertiary": "#ffffff",
              "background": "#f8f9ff",
              "surface-container-highest": "#d3e4fe",
              "on-secondary": "#ffffff",
              "surface-container": "#e5eeff",
              "secondary": "#006b5f",
              "secondary-fixed": "#71f8e4",
              "outline": "#76777d",
              "primary-container": "#131b2e",
              "inverse-primary": "#bec6e0",
              "on-error": "#ffffff",
              "secondary-fixed-dim": "#4fdbc8",
              "tertiary-container": "#191c1e",
              "on-primary-fixed-variant": "#3f465c"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "lg": "40px",
              "xl": "64px",
              "xs": "8px",
              "gutter": "24px",
              "md": "24px",
              "sm": "16px",
              "base": "4px",
              "container-max": "1440px"
      },
      "fontFamily": {
              "h3": ["Inter"],
              "body-sm": ["Inter"],
              "body-md": ["Inter"],
              "h1": ["Inter"],
              "h2": ["Inter"],
              "body-lg": ["Inter"],
              "data-tabular": ["Inter"],
              "label-caps": ["Inter"]
      },
      "fontSize": {
              "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h2": ["30px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "data-tabular": ["14px", {"lineHeight": "1", "fontWeight": "500"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
